[connections_gcs]

token = '''
type = "service_account"
project_id = "footbalprediction-414107"
private_key_id = "ccae027241adbd582a4b8c05a4d530ab9089327a"
private_key = "-----BEGIN PRIVATE KEY-----\n\
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCl6OkIEh6U3ES4\n\
LB6MU4O8rlGmHlqhCd1Hq+n+47y5DAbslF1396D9hIBCRpZGbQx5P1CPg4ZHwJq9\n\
HSXnk1KJF39gHd8emG+yE9A/vWFcuTvTPbU7VpX93yFMAzyFoMRjxoQsP1bE3Zl5\n\
9Ic1/zxbJwWxHOfbxiil9+94IxhnIXmHdYb7dFkkGQuipBs7Dtoy0Pshs4Wlf0ge\n\
WGeGRCVq5ayEUXsXIeBZUzOXe82831AmTKHmEV8vmawg0oSBuBRw2zrbTXknlP36\n\
uASn5I/Tdwh0K6qwb+79uda/Fd6W8u7OD26OTYrWWwP9OxTrfSY2rSlzdEVKEoCJ\n\
cZLRFFQLAgMBAAECggEAEgq5fgSxFFa9wa9z5PusqZyP9CTR4zhLkCCMUjPEJqAT\n\
CAV8V/BIWWQK1JTmK6Nuhf2SI6vVsut+3aOT/H0OA9WCfFp96c8Bj9fNai5h2O+r\n\
J1DLFWMC7aLRn/lWyrX4arHrAVV5TfBGi+IWar37ph1LZlQdN05IcP/80noyjFMF\n\
QOhQmp4PySU0ICk2cPM49TEw+y20grzmjF8/eFWg1YUhyeQWeiANHPx2x8qC+qAi\n\
1Aq3ANT8den41NHo2sSxSphvjNE30fQtgCiTheeWlBzXeFPiMbyhO8AYwG6migXW\n\
nmxWE0WMJ6GL0L6Jl207MVm4st5Pur0Xenv8yww8DQKBgQDSFJm97zceU00DCXAr\n\
FnrDlYruqYWEXJ62A8+l6kCUNwtvCqt5oORAkygUC8kp3pPIy8fSIbat3ldtrG1f\n\
k7v7jRBuYu8Pxl5JLO147+6tf09h366ngyquGnOJ9VjhFnvwu1cgNrJe/lTXTT3y\n\
a6mn5Wkk2qoDkOZUvbDn1opktwKBgQDKLKrRtoz4jwPL6l2BqET4d9O5qML3hC3n\n\
R45V7CxUvKUxOz8zI2y/1PV/BoF6pQDpTwEz9C1KXdt6dJuir+sUqKcbPCTwlCGW\n\
K2Q4L5uiXWtVhm/Jb6h3mWFOYSWiSACG/KwcbTteI2JfZZpB3YHlQcTgEwiOthiF\n\
TSC3La0/TQKBgFVUwM4BaKYMt+9P2hvmWZ8wEuq2OOF2rZDJI4MFD44kfaRw9Q3G\n\
aHBCVbkuwFsdaXHaNCQKRaWB9ok5zINSAr0+oznzPZ9ut8WJVjwVWSFn4NqkfNDV\n\
2nQ1klCrM5raAyXZMp6HGRS0wcliOpNJX/QunvK1TvF73dL16fGBl10pAoGAZgOl\n\
6g3wEhev9bv7lMoAi1ODbUI/pr92niYYJzj1oYhS3oWjvT0Zya4+desleGo8DH3G\n\
AJ4sIEM91Qtz4OJdf14ee/qcNRy52dlpR4SWRpZW65/bVkxWOIsXc4JHiBxGz9Y9\n\
Tla7xyOZpsNQ0/1eZv0Jx3szLTerJdAmOuf8bF0CgYAXxmiCvTBJChjSqSaiygBP\n\
tCUTeuXGU4arXHP9HtoUxx/pfX4b/y9Zx6aBeVmvEeaG1GzPOPQY5Sq2jcbFZZSI\n\
5FVdZUjrdNS++UaI+/brkr2nC58Q+oBJ5Q8XTBRXzMdTaaIiQe3rMJkOCTQ7Jo6n\n\
cW8+T0q3yU7XfgBPjztESg==\n\
-----END PRIVATE KEY-----\n"
client_email = "streamlit-python-0410@footbalprediction-414107.iam.gserviceaccount.com"
client_id = "114047689527607639710"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-python-0410%40footbalprediction-414107.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
'''
